### ISSUE TITLE
Reattempt results interpretations

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/HW-03-ajinkyapdeshmukh#1]
Greetings ajinkyadeshmukh, 

Upon reading your interpretations of model results, its clear that you rephrased the original text. This is apparent, for example, when you the results in section "Option 1: Use the Data As Is and Hope For The Best": Kappa = 0.684 in your example, yet you write in your interpretation: "Although kappa is zero and accuracy is high,...". I found a similar pattern throughout your entire submission. The purpose of the assignment was to interpret the new results. 

Please go through your submission and interpret the results accurately and resubmit by Wednesday, Nov 8th, otherwise you will not receive credit for the interpretations. For the next HW assignment, I won't be giving out a second chance.

**Comment by ajinkyapdeshmukh10** [comment]
Hi Greg, 
I've resubmitted the assignment updating the interpretations.
Thank you for considering.
