### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/HW-03-ajinkyapdeshmukh#2]
Dear ajinkyapdeshmukh -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Overall: Your feedback doesn't interpret the actual result, it rephrases the original text. In an instance or two, it looks like generated text - e.g., "Additionally, nominal variables, including logical variables, should be coded as factors. The class variable for 'train' in caret must not have level names that are reserved keywords in R (e.g., TRUE and FALSE). Consider renaming them, for instance, to 'yes' and 'no.'" Perhaps it is your text, but the syntax is not correct. 

As a result, your score is **7.4 / 10**, I gave you points for attempting to address my feedback, but I can't give more than this.

---

### Training and Data: `[7 / 10 points]`

- Reasonable choice for classification: `[6 / 6 points]`
- Narrative: `[1 / 4 points]`
- Feedback: I gave a point because you attempted to address adding narrative, but you still did very little result interpretation. 

### Fitting classification models: `[17 / 22 points]`

  - Correct application: `[16 / 16]`
  - Narrative `[1 / 6]`
  - Feedback: I gave a point because you attempted to address adding narrative, but you still did very little result interpretation. 

### Comparing models: `[6 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[1 / 5]`
  - Feedback: I gave a point because you attempted to address adding narrative, but you still did very little result interpretation. 

### Applying chosen model: `[6 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[1 / 5]`
  - Feedback: I gave a point because you attempted to address adding narrative, but you still did very little result interpretation. 

### Comparing decision boundaries: `[20 / 28 points]`

  - Correct application: `[18 / 18]`
  - Narrative: `[2 / 10]`
  - Feedback: I gave a point because you attempted to address adding narrative, but you still did very little result interpretation. 

### Overall: `[18 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[1 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- **Feedback**: you used very few commits, which means that you would be unable to revert to previous versions. 
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by ajinkyapdeshmukh10** [comment]
Hello Greg, 
Thank you for the feedback, I'll keep these things in mind for the future submissions.
